### ISSUE TITLE
Account Balance Chart issue

### ISSUE THREAD

**Issue by Greg15** [open-blockchain-explorer/tnbexplorer#78]
The chart for a particular account shows a rise in account balance, followed by a decrease in account balance, even though there have only been deposits (4 of them) into that account during that time period. There have been no withdrawals from the account during that time period.

I believe the current final balance in the chart is accurate, but the intermediate balances in the chart are off.

The issue was found on an Android phone using Chrome browser.

![Screenshot_20211108-174126](https://user-images.githubusercontent.com/70354350/140835778-0f5e76ec-4b99-4afd-948d-4efdd4d63b8a.png)

![Screenshot_20211108-174149](https://user-images.githubusercontent.com/70354350/140835866-9413e59a-5fc0-4dd9-9ca3-4bd914a1170b.png)

**Comment by tomijaga** [comment]
Thanks for reporting the issue. We will take a look at it and submit a fix for the bug soon

**Comment by tomijaga** [comment]
@Greg15 I have pushed a fix for this issue. Take a look and tell me if everything is ok from your end

**Comment by Greg15** [comment]
Looks perfect!
Each point on the graph now appears to reflect actual balance on the corresponding date.
Thanks for fixing, and thanks for the heads up.
